#!/bin/sh

set -euo 
#pipefail
printf '\33c\e[3J'

VERFILE=src/main/resources/buildno.txt
old_ver=`head -1 $VERFILE`
VERSION_NUMBER=`expr $old_ver + 1`
echo $VERSION_NUMBER > $VERFILE
TIMESTAMP=`date`
echo $TIMESTAMP >> $VERFILE

DIR="src/main/resources/static"
cp $DIR/index0.html $DIR/index.html
sed -i '' "s/__VERSION_NUMBER__/$VERSION_NUMBER/g" $DIR/index.html
sed -i '' "s/__TIMESTAMP__/$TIMESTAMP/g" $DIR/index.html

sbt stage
./deploy.sh


